### ISSUE TITLE
Spell Buff Section

### ISSUE THREAD

**Issue by Lenyarin** [phoosa/elvui_easybuff#1]
I am a Dwarf Priest playing the german client and I have the same Problem that the Spell Buff Section is greyed out under the Wanted Buffs in every Context. I updated it to the latest version this morning but it does not help. I dont think its because of the language, because the Tracking Type "Find Herbs" at the Tracking Abilities works well.

**Comment by phoosa** [comment]
It likely is related to language.  Building the Tracking options is done by looking up tracking abilities by tracking texture, while spell information is queried by name when generating the Configuration page.  I was able to avoid using name-based lookups everywhere else it seems.  I'll try and spend some time over the next week either changing how to config is generated, or adding additional language support.

**Comment by phoosa** [comment]
Try this, let me know if it works for you - if so I'll push it.

[ElvUI_EasyBuff (test).zip](https://github.com/phoosa/elvui_easybuff/files/6525670/ElvUI_EasyBuff.test.zip)

**Comment by Lenyarin** [comment]
No it does not change anything for me, sorry.

**Comment by Kabulla** [comment]
If this is any "encouragement", the test-build also does not work for me (DE-client)...
crossing my fingers ist the best I can do in support for now :-(

**Comment by Kabulla** [comment]
Anything we can help with?
Localization? testing?

**Comment by phoosa** [comment]
I found the issue that was blocking the config options from rendering - fixed in v1.4.1
There's still plenty of work to do with Localization, I'm sure there are a few strings I've missed in the enUS file.  I'll try to get them updated in the next few weeks.  With TBC finally launching, I'm sure I'll be preoccupied next week =)

**Comment by Lenyarin** [comment]
At the Germany Client it works so far. I have the options. I havent had the possiblity to test it in a group / raid. I will inform you if there are any issues. Thank you so far

**Comment by Kabulla** [comment]
> I found the issue that was blocking the config options from rendering - fixed in v1.4.1
> There's still plenty of work to do with Localization, I'm sure there are a few strings I've missed in the enUS file. I'll try to get them updated in the next few weeks. With TBC finally launching, I'm sure I'll be preoccupied next week =)

Hi phoo and thx for the great work. love it!
two things I noticed, on the fly:
- the mod does not seem to check if "stronger" buffs are on the target and tends to overwrite them (prayers, in the case of the priest
- cannot choose to cast "prayers", instead of the regular buffs in grp/raid constellation.

addition:
would you deem it feasible, to add something of a "missing buff" headcount depending on which (and "in range) the tool would either rebuff the prayer or single buffs?

again... very helpful as is and very much appreciated!

(let us know if we can give you a hand, especially on the "localization" business...

**Comment by phoosa** [comment]
Kabulla,
1) The "Greater Buffs" config is probably pushed down in the config window.  Scroll down in the Party/Raid/Battleground Context and you should see a "Greater Buffs" section.  When selected, you will cast the greater version of the buff instead of the default/lesser version when this context is active.  Example:

![image](https://user-images.githubusercontent.com/62080669/120120899-6cff8c80-c155-11eb-9b76-393a07cb80c7.png)

2) I do need to handle the "more powerful version" issue related to Early Monitoring... ie: when someone has put talent points into PW:Fort and you haven't, you cannot overwrite the PW:Fort they have cast on someone.

3) How would you prefer to see the headcount rendered?

4) I do intend to audit the Localization data, and make sure I've got all of the strings covered in the enUS file.  Once done, I would very much appreciate translation text for other languages.  Google Translate helps, but it's not always a true natural translation.

5) Side note... I've got a new version that I'll be publishing soon that includes:
- "instance checking" for the party/raid/bg contexts
- "resting checking" for the solo context
- support for the "find fish" tracking ability (go fish up your book if you haven't yet BTW!)
- buff queue refresh rate reduced to 3sec from 5 in order to reduce the chances of casting a "greater" buff when it's no longer necessary.  This is a temporary fix, I really just need to dig into the events more and auto-remove everyone the "Greater" buff was applied to instead of just the target of the cast.
It's working, I just want to test it out a bit more before I publish it.
